spring.application.name=ecommerce2

# Veritabani Baglantisi (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db?serverTimezone=UTC
spring.datasource.username=root
# NOT: Eger MySQL sifreniz farkliysa (ornegin 1234, root, vb.) asagidaki sifreyi degistirin.
spring.datasource.password=12345678

# Hibernate (Tablolari Otomatik Olusturma Ayari)
# "update" sayesinde kodda yazdigimiz Entity'ler veritabaninda tablo olarak otomatik acilir.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
